alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hosts"'
alias ll='ls -lAFh --color=auto'
alias mvn='mvn -gs "$XDG_CONFIG_HOME/maven/settings.xml"'
